#cordova plugin add cordova-plugin-geolocation --save
#cordova plugin add cordova-plugin-statusbar --save
#cordova plugin add cordova-plugin-camera --save
cordova plugin add cordova-plugin-console --save
cordova plugin add cordova-plugin-dialogs --save
cordova plugin add cordova-plugin-device --save
cordova plugin add cordova-plugin-file --save
cordova plugin add cordova-plugin-file-transfer --save
cordova plugin add cordova-plugin-sqlite --save
cordova plugin add cordova-plugin-whitelist --save
cordova plugin add ionic-plugin-keyboard --save
cordova plugin add https://github.com/starmobiledevelopers/cordova-HTTP --save
cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git --save
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git --save
cordova plugin add https://github.com/whiteoctober/cordova-plugin-app-version.git --save
cordova plugin add https://github.com/leecrossley/cordova-plugin-touchid.git --save
cordova plugin add https://starmobiledevelopers:DorothyinKansa5@github.com/transistorsoft/cordova-background-geolocation.git --save
ionic plugin add https://github.com/driftyco/ionic-plugins-deploy --save
