export const usersDocs = [
    {
      "_id": "org.couchdb.user:Sandstorm",
      "avatarName": "Sandstorm",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "sbadillo@sesafleetservices.com",
      "firstName": "Sergio",
      "lastName": "Badillo",
      "loc1": "ODESSA",
      "loc2": "MAIN",
      "locationClass": "HALLIBURTON ODESSA-MAIN: TOPPER",
      "middleName": "",
      "name": "Sandstorm",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Sandstorm",
      "technician": "Badillo, Sergio ",
      "type": "user",
      "uidString1": "597",
      "userClass": "TOPPER",
      "userUuid": "Badillo597Sergio"
    },
    {
      "_id": "org.couchdb.user:Omega",
      "avatarName": "Omega",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "tcain@sesafleetservices.com",
      "firstName": "Timothy",
      "lastName": "Cain",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: E-TECH",
      "middleName": "",
      "name": "Omega",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Omega",
      "technician": "Cain, Timothy ",
      "type": "user",
      "uidString1": "924",
      "userClass": "E-TECH",
      "userUuid": "Cain924Timothy"
    },
    {
      "_id": "org.couchdb.user:Jumper",
      "avatarName": "Jumper",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "odelagarza@sesafleetservices.com",
      "firstName": "Oscar",
      "lastName": "De La Garza",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: M-TECH",
      "middleName": "",
      "name": "Jumper",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Jumper",
      "technician": "De La Garza, Oscar ",
      "type": "user",
      "uidString1": "557",
      "userClass": "M-TECH",
      "userUuid": "De La Garza557Oscar"
    },
    {
      "_id": "org.couchdb.user:Tsunami",
      "avatarName": "Tsunami",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "idelarosa@sesafleetservices.com",
      "firstName": "Irvin",
      "lastName": "De La Rosa",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: M-TECH",
      "middleName": "",
      "name": "Tsunami",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Tsunami",
      "technician": "De La Rosa, Irvin ",
      "type": "user",
      "uidString1": "128",
      "userClass": "M-TECH",
      "userUuid": "De La Rosa128Irvin"
    },
    {
      "_id": "org.couchdb.user:Blitz",
      "avatarName": "Blitz",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "gdiaz@sesafleetservices.com",
      "firstName": "Gonzalo",
      "lastName": "Diaz",
      "loc1": "ODESSA",
      "loc2": "MAIN",
      "locationClass": "HALLIBURTON ODESSA-MAIN: M-TECH",
      "middleName": "",
      "name": "Blitz",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Blitz",
      "technician": "Diaz, Gonzalo ",
      "type": "user",
      "uidString1": "509",
      "userClass": "M-TECH",
      "userUuid": "Diaz509Gonzalo"
    },
    {
      "_id": "org.couchdb.user:Pivot",
      "avatarName": "Pivot",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "hescobar@sesafleetservices.com",
      "firstName": "Horacio",
      "lastName": "Escobar",
      "loc1": "SHAWNEE",
      "loc2": "MAIN",
      "locationClass": "KEANE SHAWNEE-MAIN: M-TECH",
      "middleName": "",
      "name": "Pivot",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Pivot",
      "technician": "Escobar, Horacio ",
      "type": "user",
      "uidString1": "103",
      "userClass": "M-TECH",
      "userUuid": "Escobar103Horacio"
    },
    {
      "_id": "org.couchdb.user:Riddler",
      "avatarName": "Riddler",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "eflores@sesafleetservices.com",
      "firstName": "Eric",
      "lastName": "Flores",
      "loc1": "ODESSA",
      "loc2": "MAIN",
      "locationClass": "HALLIBURTON ODESSA-MAIN: M-TECH",
      "middleName": "",
      "name": "Riddler",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Riddler",
      "technician": "Flores, Eric ",
      "type": "user",
      "uidString1": "194",
      "userClass": "M-TECH",
      "userUuid": "Flores194Eric"
    },
    {
      "_id": "org.couchdb.user:Lancer",
      "avatarName": "Lancer",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "lgarcia@sesafleetservices.com",
      "firstName": "Louis",
      "lastName": "Garcia",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: E-TECH",
      "middleName": "",
      "name": "Lancer",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Lancer",
      "technician": "Garcia, Louis ",
      "type": "user",
      "uidString1": "701",
      "userClass": "E-TECH",
      "userUuid": "Garcia701Louis"
    },
    {
      "_id": "org.couchdb.user:Starburst",
      "avatarName": "Starburst",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "egonzález@sesafleetservices.com",
      "firstName": "Eduardo",
      "lastName": "González",
      "loc1": "BROWNFIELD",
      "loc2": "PUMPSHOP",
      "locationClass": "HALLIBURTON BROWNFIELD-PUMPSHOP: M-TECH",
      "middleName": "",
      "name": "Starburst",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Starburst",
      "technician": "González, Eduardo ",
      "type": "user",
      "uidString1": "672",
      "userClass": "M-TECH",
      "userUuid": "González672Eduardo"
    },
    {
      "_id": "org.couchdb.user:Thunder",
      "avatarName": "Thunder",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "igonzález@sesafleetservices.com",
      "firstName": "Irving",
      "lastName": "González",
      "loc1": "SHAWNEE",
      "loc2": "MAIN",
      "locationClass": "KEANE SHAWNEE-MAIN: M-TECH",
      "middleName": "",
      "name": "Thunder",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Thunder",
      "technician": "González, Irving ",
      "type": "user",
      "uidString1": "148",
      "userClass": "M-TECH",
      "userUuid": "González148Irving"
    },
    {
      "_id": "org.couchdb.user:Doctor",
      "avatarName": "Doctor",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "kgonzález@sesafleetservices.com",
      "firstName": "Kevin",
      "lastName": "González",
      "loc1": "BROWNFIELD",
      "loc2": "PUMPSHOP",
      "locationClass": "HALLIBURTON BROWNFIELD-PUMPSHOP: M-TECH",
      "middleName": "",
      "name": "Doctor",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Doctor",
      "technician": "González, Kevin ",
      "type": "user",
      "uidString1": "383",
      "userClass": "M-TECH",
      "userUuid": "González383Kevin"
    },
    {
      "_id": "org.couchdb.user:Arrow",
      "avatarName": "Arrow",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "slongoria@sesafleetservices.com",
      "firstName": "Salvador",
      "lastName": "Longoria",
      "loc1": "ODESSA",
      "loc2": "MAIN",
      "locationClass": "HALLIBURTON ODESSA-MAIN: E-TECH",
      "middleName": "",
      "name": "Arrow",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Arrow",
      "technician": "Longoria, Salvador ",
      "type": "user",
      "uidString1": "526",
      "userClass": "E-TECH",
      "userUuid": "Longoria526Salvador"
    },
    {
      "_id": "org.couchdb.user:Phantom",
      "avatarName": "Phantom",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "jmarroquin@sesafleetservices.com",
      "firstName": "José",
      "lastName": "Marroquin",
      "loc1": "SHAWNEE",
      "loc2": "MAIN",
      "locationClass": "KEANE SHAWNEE-MAIN: M-TECH",
      "middleName": "Luis",
      "name": "Phantom",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Phantom",
      "technician": "Marroquin, José Luis",
      "type": "user",
      "uidString1": "699",
      "userClass": "M-TECH",
      "userUuid": "Marroquin699José"
    },
    {
      "_id": "org.couchdb.user:Hercules",
      "avatarName": "Hercules",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "jmartinez@sesafleetservices.com",
      "firstName": "Julio",
      "lastName": "Martinez",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: M-TECH",
      "middleName": "",
      "name": "Hercules",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Hercules",
      "technician": "Martinez, Julio ",
      "type": "user",
      "uidString1": "463",
      "userClass": "M-TECH",
      "userUuid": "Martinez463Julio"
    },
    {
      "_id": "org.couchdb.user:Thorne",
      "avatarName": "Thorne",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "amedina@sesafleetservices.com",
      "firstName": "Adan",
      "lastName": "Medina",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: M-TECH",
      "middleName": "",
      "name": "Thorne",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Thorne",
      "technician": "Medina, Adan ",
      "type": "user",
      "uidString1": "542",
      "userClass": "M-TECH",
      "userUuid": "Medina542Adan"
    },
    {
      "_id": "org.couchdb.user:Shadow",
      "avatarName": "Shadow",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "mmedina@sesafleetservices.com",
      "firstName": "Miguel",
      "lastName": "Medina",
      "loc1": "SHAWNEE",
      "loc2": "MAIN",
      "locationClass": "KEANE SHAWNEE-MAIN: M-TECH",
      "middleName": "",
      "name": "Shadow",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Shadow",
      "technician": "Medina, Miguel ",
      "type": "user",
      "uidString1": "863",
      "userClass": "M-TECH",
      "userUuid": "Medina863Miguel"
    },
    {
      "_id": "org.couchdb.user:Drake",
      "avatarName": "Drake",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "jmendez@sesafleetservices.com",
      "firstName": "José",
      "lastName": "Mendez",
      "loc1": "ODESSA",
      "loc2": "MAIN",
      "locationClass": "HALLIBURTON ODESSA-MAIN: TOPPER",
      "middleName": "Luis",
      "name": "Drake",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Drake",
      "technician": "Mendez, José Luis",
      "type": "user",
      "uidString1": "258",
      "userClass": "TOPPER",
      "userUuid": "Mendez258José"
    },
    {
      "_id": "org.couchdb.user:Nightshade",
      "avatarName": "Nightshade",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "omontalvan@sesafleetservices.com",
      "firstName": "Oscar",
      "lastName": "Montalvan",
      "loc1": "ODESSA",
      "loc2": "MAIN",
      "locationClass": "HALLIBURTON ODESSA-MAIN: E-TECH",
      "middleName": "",
      "name": "Nightshade",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Nightshade",
      "technician": "Montalvan, Oscar ",
      "type": "user",
      "uidString1": "824",
      "userClass": "E-TECH",
      "userUuid": "Montalvan824Oscar"
    },
    {
      "_id": "org.couchdb.user:Prodigy",
      "avatarName": "Prodigy",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "cmontes@sesafleetservices.com",
      "firstName": "Carlos",
      "lastName": "Montes",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: M-TECH",
      "middleName": "",
      "name": "Prodigy",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Prodigy",
      "technician": "Montes, Carlos ",
      "type": "user",
      "uidString1": "977",
      "userClass": "M-TECH",
      "userUuid": "Montes977Carlos"
    },
    {
      "_id": "org.couchdb.user:Pyro",
      "avatarName": "Pyro",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "eocañas@sesafleetservices.com",
      "firstName": "Elias",
      "lastName": "Ocañas",
      "loc1": "SHAWNEE",
      "loc2": "MAIN",
      "locationClass": "KEANE SHAWNEE-MAIN: M-TECH",
      "middleName": "",
      "name": "Pyro",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Pyro",
      "technician": "Ocañas, Elias ",
      "type": "user",
      "uidString1": "29",
      "userClass": "M-TECH",
      "userUuid": "Ocañas29Elias"
    },
    {
      "_id": "org.couchdb.user:Vise",
      "avatarName": "Vise",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "jochoae@sesafleetservices.com",
      "firstName": "Joel",
      "lastName": "Ochoa",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: E-TECH",
      "middleName": "E.",
      "name": "Vise",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Vise",
      "technician": "Ochoa, Joel E.",
      "type": "user",
      "uidString1": "732",
      "userClass": "E-TECH",
      "userUuid": "Ochoa732Joel"
    },
    {
      "_id": "org.couchdb.user:Lancer",
      "avatarName": "Lancer",
      "avtrNameAsUser": true,
      "clntCmpny": "SESA",
      "email": "jochoa@sesafleetservices.com",
      "firstName": "Joel",
      "lastName": "Ochoa",
      "loc1": "WESLACO",
      "loc2": "SHOP",
      "locationClass": "SESA WESLACO-SHOP: M-TECH",
      "middleName": "",
      "name": "Lancer",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "EXPNSLABOR",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Lancer",
      "technician": "Ochoa, Joel ",
      "type": "user",
      "uidString1": "737",
      "userClass": "M-TECH",
      "userUuid": "Ochoa737Joel"
    },
    {
      "_id": "org.couchdb.user:Paragon",
      "avatarName": "Paragon",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "jperalez@sesafleetservices.com",
      "firstName": "Juan",
      "lastName": "Peralez",
      "loc1": "BROWNFIELD",
      "loc2": "PUMPSHOP",
      "locationClass": "HALLIBURTON BROWNFIELD-PUMPSHOP: M-TECH",
      "middleName": "",
      "name": "Paragon",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Paragon",
      "technician": "Peralez, Juan ",
      "type": "user",
      "uidString1": "283",
      "userClass": "M-TECH",
      "userUuid": "Peralez283Juan"
    },
    {
      "_id": "org.couchdb.user:Cropas",
      "avatarName": "Cropas",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "jrendón@sesafleetservices.com",
      "firstName": "Jimmy",
      "lastName": "Rendón",
      "loc1": "ODESSA",
      "loc2": "MAIN",
      "locationClass": "HALLIBURTON ODESSA-MAIN: M-TECH",
      "middleName": "",
      "name": "Cropas",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Cropas",
      "technician": "Rendón, Jimmy ",
      "type": "user",
      "uidString1": "935",
      "userClass": "M-TECH",
      "userUuid": "Rendón935Jimmy"
    },
    {
      "_id": "org.couchdb.user:Dagger",
      "avatarName": "Dagger",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "jrico@sesafleetservices.com",
      "firstName": "José",
      "lastName": "Rico",
      "loc1": "ODESSA",
      "loc2": "MAIN",
      "locationClass": "HALLIBURTON ODESSA-MAIN: TOPPER",
      "middleName": "Luis",
      "name": "Dagger",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Dagger",
      "technician": "Rico, José Luis",
      "type": "user",
      "uidString1": "128",
      "userClass": "TOPPER",
      "userUuid": "Rico128José"
    },
    {
      "_id": "org.couchdb.user:Baron",
      "avatarName": "Baron",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "rtijerina@sesafleetservices.com",
      "firstName": "René",
      "lastName": "Tijerina",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: M-TECH",
      "middleName": "",
      "name": "Baron",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Baron",
      "technician": "Tijerina, René ",
      "type": "user",
      "uidString1": "170",
      "userClass": "M-TECH",
      "userUuid": "Tijerina170René"
    },
    {
      "_id": "org.couchdb.user:Lightfoot",
      "avatarName": "Lightfoot",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "atorres@sesafleetservices.com",
      "firstName": "Alex",
      "lastName": "Torres",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: M-TECH",
      "middleName": "",
      "name": "Lightfoot",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Lightfoot",
      "technician": "Torres, Alex ",
      "type": "user",
      "uidString1": "51",
      "userClass": "M-TECH",
      "userUuid": "Torres51Alex"
    },
    {
      "_id": "org.couchdb.user:Totem",
      "avatarName": "Totem",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "etovar@sesafleetservices.com",
      "firstName": "Eduardo",
      "lastName": "Tovar",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: M-TECH",
      "middleName": "",
      "name": "Totem",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Totem",
      "technician": "Tovar, Eduardo ",
      "type": "user",
      "uidString1": "783",
      "userClass": "M-TECH",
      "userUuid": "Tovar783Eduardo"
    },
    {
      "_id": "org.couchdb.user:Patriot",
      "avatarName": "Patriot",
      "avtrNameAsUser": true,
      "clntCmpny": "HALLIBURTON",
      "email": "ptreviño@sesafleetservices.com",
      "firstName": "Pete",
      "lastName": "Treviño",
      "loc1": "ODESSA",
      "loc2": "MAIN",
      "locationClass": "HALLIBURTON ODESSA-MAIN: E-TECH",
      "middleName": "",
      "name": "Patriot",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Patriot",
      "technician": "Treviño, Pete ",
      "type": "user",
      "uidString1": "327",
      "userClass": "E-TECH",
      "userUuid": "Treviño327Pete"
    },
    {
      "_id": "org.couchdb.user:Dragon",
      "avatarName": "Dragon",
      "avtrNameAsUser": true,
      "clntCmpny": "KEANE",
      "email": "hvela@sesafleetservices.com",
      "firstName": "Heriberto",
      "lastName": "Vela",
      "loc1": "SPRINGTOWN",
      "loc2": "MAIN",
      "locationClass": "KEANE SPRINGTOWN-MAIN: M-TECH",
      "middleName": "",
      "name": "Dragon",
      "password": "$ES@4328fLeeTSrvcs",
      "pyrlClass": "BILLABLE",
      "roles": [
        "onSiteUser"
      ],
      "techUUID": "Dragon",
      "technician": "Vela, Heriberto ",
      "type": "user",
      "uidString1": "217",
      "userClass": "M-TECH",
      "userUuid": "Vela217Heriberto"
    }
]