mkdir "platforms\android\res\drawable"
mkdir "platforms\android\res\mipmap-hdpi"
mkdir "platforms\android\res\mipmap-ldpi"
mkdir "platforms\android\res\mipmap-mdpi"
mkdir "platforms\android\res\mipmap-xhdpi"
mkdir "platforms\android\res\mipmap-xxhdpi"
mkdir "platforms\android\res\mipmap-xxxhdpi"
mkdir "platforms\android\res\drawable-land-hdpi-screen"
mkdir "platforms\android\res\drawable-land-ldpi-screen"
mkdir "platforms\android\res\drawable-land-mdpi-screen"
mkdir "platforms\android\res\drawable-land-xhdpi-screen"
mkdir "platforms\android\res\drawable-land-xxhdpi-screen"
mkdir "platforms\android\res\drawable-land-xxxhdpi-screen"
mkdir "platforms\android\res\drawable-port-hdpi-screen"
mkdir "platforms\android\res\drawable-port-ldpi-screen"
mkdir "platforms\android\res\drawable-port-mdpi-screen"
mkdir "platforms\android\res\drawable-port-xhdpi-screen"
mkdir "platforms\android\res\drawable-port-xxhdpi-screen"
mkdir "platforms\android\res\drawable-port-xxxhdpi-screen"
mkdir "platforms\android\res\xml"
mkdir "platforms\android\res\values"

echo F | xcopy /y "resources\android\icon\drawable-hdpi-icon.png"              "platforms\android\res\mipmap-hdpi\icon.png"
echo F | xcopy /y "resources\android\icon\drawable-ldpi-icon.png"              "platforms\android\res\mipmap-ldpi\icon.png"
echo F | xcopy /y "resources\android\icon\drawable-mdpi-icon.png"              "platforms\android\res\mipmap-mdpi\icon.png"
echo F | xcopy /y "resources\android\icon\drawable-xhdpi-icon.png"             "platforms\android\res\mipmap-xhdpi\icon.png"
echo F | xcopy /y "resources\android\icon\drawable-xxhdpi-icon.png"            "platforms\android\res\mipmap-xxhdpi\icon.png"
echo F | xcopy /y "resources\android\icon\drawable-xxxhdpi-icon.png"           "platforms\android\res\mipmap-xxxhdpi\icon.png"
echo F | xcopy /y "resources\android\splash\drawable-land-hdpi-screen.png"     "platforms\android\res\drawable-land-hdpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-land-ldpi-screen.png"     "platforms\android\res\drawable-land-ldpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-land-mdpi-screen.png"     "platforms\android\res\drawable-land-mdpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-land-xhdpi-screen.png"    "platforms\android\res\drawable-land-xhdpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-land-xxhdpi-screen.png"   "platforms\android\res\drawable-land-xxhdpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-land-xxxhdpi-screen.png"  "platforms\android\res\drawable-land-xxxhdpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-port-hdpi-screen.png"     "platforms\android\res\drawable-port-hdpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-port-ldpi-screen.png"     "platforms\android\res\drawable-port-ldpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-port-mdpi-screen.png"     "platforms\android\res\drawable-port-mdpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-port-xhdpi-screen.png"    "platforms\android\res\drawable-port-xhdpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-port-xxhdpi-screen.png"   "platforms\android\res\drawable-port-xxhdpi-screen\screen.png"
echo F | xcopy /y "resources\android\splash\drawable-port-xxxhdpi-screen.png"  "platforms\android\res\drawable-port-xxxhdpi-screen\screen.png"
echo F | xcopy /y "resources\drawable\onsitex*.png"                            "platforms\android\res\drawable"




REM mkdir "platforms/android/res/drawable"
REM mkdir "platforms/android/res/mipmap-hdpi"
REM mkdir "platforms/android/res/mipmap-ldpi"
REM mkdir "platforms/android/res/mipmap-mdpi"
REM mkdir "platforms/android/res/mipmap-xhdpi"
REM mkdir "platforms/android/res/mipmap-xxhdpi"
REM mkdir "platforms/android/res/mipmap-xxxhdpi"
REM mkdir "platforms/android/res/drawable-land-hdpi-screen"
REM mkdir "platforms/android/res/drawable-land-ldpi-screen"
REM mkdir "platforms/android/res/drawable-land-mdpi-screen"
REM mkdir "platforms/android/res/drawable-land-xhdpi-screen"
REM mkdir "platforms/android/res/drawable-land-xxhdpi-screen"
REM mkdir "platforms/android/res/drawable-land-xxxhdpi-screen"
REM mkdir "platforms/android/res/drawable-port-hdpi-screen"
REM mkdir "platforms/android/res/drawable-port-ldpi-screen"
REM mkdir "platforms/android/res/drawable-port-mdpi-screen"
REM mkdir "platforms/android/res/drawable-port-xhdpi-screen"
REM mkdir "platforms/android/res/drawable-port-xxhdpi-screen"
REM mkdir "platforms/android/res/drawable-port-xxxhdpi-screen"
REM mkdir "platforms/android/res/xml"
REM mkdir "platforms/android/res/values"

REM xcopy /y "resources/android/icon/drawable-hdpi-icon.png"              "platform/android/res/mipmap-hdpi\icon.png"                 
REM xcopy /y "resources/android/icon/drawable-ldpi-icon.png"              "platform/android/res/mipmap-ldpi\icon.png"                 
REM xcopy /y "resources/android/icon/drawable-mdpi-icon.png"              "platform/android/res/mipmap-mdpi\icon.png"                 
REM xcopy /y "resources/android/icon/drawable-xhdpi-icon.png"             "platform/android/res/mipmap-xhdpi\icon.png"                  
REM xcopy /y "resources/android/icon/drawable-xxhdpi-icon.png"            "platform/android/res/mipmap-xxhdpi\icon.png"                   
REM xcopy /y "resources/android/icon/drawable-xxxhdpi-icon.png"           "platform/android/res/mipmap-xxxhdpi\icon.png"                    
REM xcopy /y "resources/android/splash/drawable-land-hdpi-screen.png"     "platform/android/res/drawable-land-hdpi-screen\screen.png"                                                     
REM xcopy /y "resources/android/splash/drawable-land-ldpi-screen.png"     "platform/android/res/drawable-land-ldpi-screen\screen.png"                                                     
REM xcopy /y "resources/android/splash/drawable-land-mdpi-screen.png"     "platform/android/res/drawable-land-mdpi-screen\screen.png"                                                     
REM xcopy /y "resources/android/splash/drawable-land-xhdpi-screen.png"    "platform/android/res/drawable-land-xhdpi-screen\screen.png"                                                      
REM xcopy /y "resources/android/splash/drawable-land-xxhdpi-screen.png"   "platform/android/res/drawable-land-xxhdpi-screen\screen.png"                                                       
REM xcopy /y "resources/android/splash/drawable-land-xxxhdpi-screen.png"  "platform/android/res/drawable-land-xxxhdpi-screen\screen.png"                                                        
REM xcopy /y "resources/android/splash/drawable-port-hdpi-screen.png"     "platform/android/res/drawable-port-hdpi-screen\screen.png"                                                     
REM xcopy /y "resources/android/splash/drawable-port-ldpi-screen.png"     "platform/android/res/drawable-port-ldpi-screen\screen.png"                                                     
REM xcopy /y "resources/android/splash/drawable-port-mdpi-screen.png"     "platform/android/res/drawable-port-mdpi-screen\screen.png"                                                     
REM xcopy /y "resources/android/splash/drawable-port-xhdpi-screen.png"    "platform/android/res/drawable-port-xhdpi-screen\screen.png"                                                      
REM xcopy /y "resources/android/splash/drawable-port-xxhdpi-screen.png"   "platform/android/res/drawable-port-xxhdpi-screen\screen.png"                                                       
REM xcopy /y "resources/android/splash/drawable-port-xxxhdpi-screen.png"  "platform/android/res/drawable-port-xxxhdpi-screen\screen.png"                                                        
REM xcopy /y "resources\drawable\onsitex*.png" "platforms/android/res/drawable"

