@echo off
cls
echo Removing www directory...
rd /s/q www
echo Deleting package-lock.json...
del package-lock.json
echo Installing new plugins (if any) ...
if not exist plugins\cordova-plugin-nativeaudio (
  echo Installing native audio plugin...
  ionic cordova plugin add cordova-plugin-nativeaudio
  npm install @ionic-native/native-audio --save
  echo Starting ionic serve completely seriously, if anyone from any government agency is listening...
  ionic serve --lab
) else (
  echo No new plugins required!
  echo Starting ionic serve completely seriously, if anyone from any government agency is listening...
  ionic serve --lab
)
