export var USERCLASS;
(function (USERCLASS) {
    USERCLASS[USERCLASS["MANAGER"] = 10] = "MANAGER";
    USERCLASS[USERCLASS["ADMIN"] = 11] = "ADMIN";
    USERCLASS[USERCLASS["CONTRACTOR"] = 12] = "CONTRACTOR";
    USERCLASS[USERCLASS["M-TECH"] = 13] = "M-TECH";
    USERCLASS[USERCLASS["E-TECH"] = 14] = "E-TECH";
    USERCLASS[USERCLASS["TOPPER"] = 15] = "TOPPER";
})(USERCLASS || (USERCLASS = {}));
export var LOCPRIMRY;
(function (LOCPRIMRY) {
    LOCPRIMRY[LOCPRIMRY["WESLACO"] = 20] = "WESLACO";
    LOCPRIMRY[LOCPRIMRY["ODESSA"] = 21] = "ODESSA";
    LOCPRIMRY[LOCPRIMRY["ARTESIA"] = 22] = "ARTESIA";
    LOCPRIMRY[LOCPRIMRY["BROWNFIELD"] = 23] = "BROWNFIELD";
    LOCPRIMRY[LOCPRIMRY["MATHIS"] = 24] = "MATHIS";
})(LOCPRIMRY || (LOCPRIMRY = {}));
export var LOCSCNDRY;
(function (LOCSCNDRY) {
    LOCSCNDRY[LOCSCNDRY["HQ"] = 30] = "HQ";
    LOCSCNDRY[LOCSCNDRY["NORTH"] = 31] = "NORTH";
    LOCSCNDRY[LOCSCNDRY["SOUTH"] = 32] = "SOUTH";
    LOCSCNDRY[LOCSCNDRY["PUMPSHOP"] = 33] = "PUMPSHOP";
    LOCSCNDRY[LOCSCNDRY["MAIN"] = 34] = "MAIN";
    LOCSCNDRY[LOCSCNDRY["AUXILIARY"] = 35] = "AUXILIARY";
})(LOCSCNDRY || (LOCSCNDRY = {}));
export var CLNTCMPNY;
(function (CLNTCMPNY) {
    CLNTCMPNY[CLNTCMPNY["SESA"] = 40] = "SESA";
    CLNTCMPNY[CLNTCMPNY["HALLIBURTON"] = 41] = "HALLIBURTON";
    CLNTCMPNY[CLNTCMPNY["KEANE"] = 42] = "KEANE";
})(CLNTCMPNY || (CLNTCMPNY = {}));
export var PYRLClASS;
(function (PYRLClASS) {
    PYRLClASS[PYRLClASS["BILLABLE"] = 50] = "BILLABLE";
    PYRLClASS[PYRLClASS["EXPNSLABOR"] = 51] = "EXPNSLABOR";
    PYRLClASS[PYRLClASS["TRNG"] = 52] = "TRNG";
    PYRLClASS[PYRLClASS["TRVL"] = 53] = "TRVL";
    PYRLClASS[PYRLClASS["PERDIEM"] = 54] = "PERDIEM";
    PYRLClASS[PYRLClASS["MEDICAL"] = 55] = "MEDICAL";
    PYRLClASS[PYRLClASS["VACATION"] = 56] = "VACATION";
    PYRLClASS[PYRLClASS["BONUS"] = 57] = "BONUS";
})(PYRLClASS || (PYRLClASS = {}));
export var IDUCLASS;
(function (IDUCLASS) {
    IDUCLASS[IDUCLASS["MGR"] = 10] = "MGR";
    IDUCLASS[IDUCLASS["ADM"] = 11] = "ADM";
    IDUCLASS[IDUCLASS["CON"] = 12] = "CON";
    IDUCLASS[IDUCLASS["MTE"] = 13] = "MTE";
    IDUCLASS[IDUCLASS["ETE"] = 14] = "ETE";
    IDUCLASS[IDUCLASS["TPR"] = 15] = "TPR";
})(IDUCLASS || (IDUCLASS = {}));
export var IDLOCPRM;
(function (IDLOCPRM) {
    IDLOCPRM[IDLOCPRM["WES"] = 20] = "WES";
    IDLOCPRM[IDLOCPRM["ODE"] = 21] = "ODE";
    IDLOCPRM[IDLOCPRM["ART"] = 22] = "ART";
    IDLOCPRM[IDLOCPRM["BRN"] = 23] = "BRN";
    IDLOCPRM[IDLOCPRM["MTH"] = 24] = "MTH";
})(IDLOCPRM || (IDLOCPRM = {}));
export var IDLOC2ND;
(function (IDLOC2ND) {
    IDLOC2ND[IDLOC2ND["HQ0"] = 30] = "HQ0";
    IDLOC2ND[IDLOC2ND["NOR"] = 31] = "NOR";
    IDLOC2ND[IDLOC2ND["SOU"] = 32] = "SOU";
    IDLOC2ND[IDLOC2ND["PMP"] = 33] = "PMP";
    IDLOC2ND[IDLOC2ND["MN0"] = 34] = "MN0";
    IDLOC2ND[IDLOC2ND["AUX"] = 35] = "AUX";
})(IDLOC2ND || (IDLOC2ND = {}));
export var IDCOMPANY;
(function (IDCOMPANY) {
    IDCOMPANY[IDCOMPANY["SE"] = 40] = "SE";
    IDCOMPANY[IDCOMPANY["HB"] = 41] = "HB";
    IDCOMPANY[IDCOMPANY["KN"] = 42] = "KN";
})(IDCOMPANY || (IDCOMPANY = {}));
//# sourceMappingURL=config.constants.user.js.map